version: 2
registries:
  npm-registry-npm-fontawesome-com:
    type: npm-registry
    url: https://npm.fontawesome.com
    token: "${{secrets.NPM_REGISTRY_NPM_FONTAWESOME_COM_TOKEN}}"

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 99
    ignore:
      - dependency-name: gatsby
        versions:
          - 2.32.7
          - 3.0.3
          - 3.0.4
          - 3.1.0
          - 3.1.1
          - 3.1.2
          - 3.1.3
          - 3.2.0
          - 3.2.1
          - 3.3.0
          - 3.3.1
      - dependency-name: gatsby-transformer-remark
        versions:
          - 4.0.0
      - dependency-name: gatsby-source-contentful
        versions:
          - 4.5.2
          - 4.5.3
          - 5.0.1
          - 5.0.2
          - 5.0.3
          - 5.1.0
          - 5.1.1
          - 5.1.2
          - 5.1.3
          - 5.2.0
          - 5.2.1
          - 5.3.0
      - dependency-name: gatsby-plugin-sass
        versions:
          - 4.0.2
          - 4.1.0
          - 4.2.0
          - 4.3.0
      - dependency-name: npm-check-updates
        versions:
          - 11.1.2
    registries:
      - npm-registry-npm-fontawesome-com
