# /*-----------------------------------------------------------------------------*

# FILE
# .github/ranger.yml

# DESCRIPTION
# Configuration file for Repo Ranger.

# *-----------------------------------------------------------------------------*/

labels:
  # All PRs labeled merge get automatically merged
  merge: merge
