name: Auto Label PRs

on:
  pull_request:
    branches:
    - '*'

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: "Auto Label PRs"
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
