# /*-----------------------------------------------------------------------------*

# FILE
# .github/workflows/label-PRs.yml

# DESCRIPTION
# Action file for Label PRs Github workflow.

# *-----------------------------------------------------------------------------*/

name: "Label PRs"

on:
  issues:
    types: [opened, edited, milestoned]
  pull_request_target:
    types: [opened]

jobs:

  labeler:
    runs-on: ubuntu-latest

    steps:
    - name: Check Labels
      id: labeler
      uses: jimschubert/labeler-action@v2
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
