name: "PR Labeler"

on:
  workflow_run:
    workflows: ["Update Production"]
    types:
      - completed

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: "Label PRs"
      uses: srvaroa/labeler@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
